package cz.muni.fi.pv168.project.ui.dialog;

import cz.muni.fi.pv168.project.model.Ingredient;
import cz.muni.fi.pv168.project.model.Range;
import cz.muni.fi.pv168.project.model.RecipeCategory;
import cz.muni.fi.pv168.project.model.RecipeFilter;

import java.awt.*;

/**
 * Represents a dialog for configuring and applying filters to recipes.
 *
 * This dialog allows users to specify filter criteria such as ingredients, recipe categories,
 * and desired calorie ranges.
 *
 * @author Marek Eibel
 */
public class RecipeFilterDialog extends EntityDialog<RecipeFilter> {

    /**
     * Creates new RecipeFilterDialog object.
     */
    public RecipeFilterDialog() {
        super(new Dimension(800, 600)); // TODO: create dialog
    }

    /**
     * Gets the RecipeFilter generated by the user input inside a dialog window.
     *
     * @return A RecipeFilter with values for ingredients, categories, and calorie ranges.
     */
    @Override
    RecipeFilter getEntity() {
        return new RecipeFilter(Ingredient.getListOfIngredients(), RecipeCategory.getListOfCategories(), new Range(10, 300), new Range(0, 120)); // TODO: generate RecipeFilter according to the user input data
    }
}
